### ISSUE TITLE
"high" CPU usage

### ISSUE THREAD

**Issue by Maxcension** [tncga/whats-up-darkness#3]
My CPU is not very very good (Intel N3450, 4cores @ 2,2ghz), but i don't think this CPU usage is normal for a theme? Especially since it wasn't using my CPU as much before, even chrome with Youtube & Twitter don't using it as much.
Thaaanks!
![2019-05-31 14_53_00-Gestionnaire des tâches](https://user-images.githubusercontent.com/10364593/58707019-f38d0200-83b3-11e9-8615-e0568b9eedf9.png)

**Comment by gokberkakdeniz** [comment]
Electron sometimes can be buggy. I do not use Windows so much, but when I use Windows, I do not face with this issue. Have you ever noticed weird behaviour when you do spesific thing or something occured (new message delivered etc.)? Does it occur every time?

Also you may try building from source with different versions (v4.2.3, v5.x) of Electron.

**Comment by Maxcension** [comment]
The app works well when i reboot my PC, but after a while, the CPU usage is increasing.
I will try and i'll keep you updated.

**Comment by Maxcension** [comment]
So,
I built it with Electron 6.0 beta 5, and when the app is in background (reduce in the taskbar), it doesn't use my CPU, even if i receive a message.
When the app is open and i do nothing, the app use like 4-6% of my CPU.
But when i use it, the app seems to blow a fuse with my CPU.

I made a video of it so i'm gonna upload it on Youtube and send it here in like 1 hour maximum i think..

**Comment by gokberkakdeniz** [comment]
Also, can you try latest version that uses less resource?

**Comment by Maxcension** [comment]
Yeah, i'll try with Electron 5.0.2!
The video is still uploading, sorry my connection is very low sometimes.

**Comment by gokberkakdeniz** [comment]
Oops... I mean latest version of whats-up-darkness, not Electron. So that, i can compare what I have changed in the source code. But you try Electron, too.

**Comment by Maxcension** [comment]
I was using the latest version when i post the issue, sorry i didn't say it
I think when i was used the 2.0.5 version, i didn't have this problem

**Comment by Maxcension** [comment]
https://youtu.be/5SgifZpirsg
So,
With Electron 5.0.2, the CPU usage spike that we can see in the video is a bit smaller (like 65% instead of 75% with Electron 6.0) but it's still here.
I tried to downgrade to the 2.0.5 version that i used so far but i can't because it forces me to update to 2.0.7.
(don't pay attention to the sound of the video, i speak in french to s.one in it and the blowing noise doesn't come from the PC with WPP (it's fan-less)).

**Comment by gokberkakdeniz** [comment]
Version 2.0.5 and 2.0.7 are pretty much the same. I don't think those changes make this extreme cpu usage. 😕 All changes from 2.0.5 to 2.0.7 you can see from here https://github.com/tncga/whats-up-darkness/compare/2.0.5...2.0.7.1 

The code in `preload.js` may cause problem **but** it exists since _version 2.0.3_:
```
  // Watch 'Click to update WhatsApp' alert
  checkElement(".m6ZEb").then(el => {
    el.style.display="none"
    console.log("Update alert removed.")
  })
```

> I tried to downgrade to the 2.0.5 version that i used so far but i can't because it forces me to update to 2.0.7.

Thanks for information. Actually, this is bug. I just fixed it.  Now you can test this version:
`git clone -b '2.0.5' --single-branch --depth 1 https://github.com/tncga/whats-up-darkness.git`
Change the 24th line in `main.js` with `const callback_no = callback_uptodate`
Change 35th line in `package.json` with `		"electron": "4.1.4"`
Now you can build.

**Comment by Maxcension** [comment]
So,
This bug appears in my other PC with an i5 460M and W7, but not this much, wpp uses "only" 30% max in 2.0.7 (but this CPU is more powerful).

But uuuh, do i doing something wrong?

![2019-06-01 00_53_02-Window](https://user-images.githubusercontent.com/10364593/58738831-ca965c80-8407-11e9-8a49-e63e72042a15.png)

**Comment by gokberkakdeniz** [comment]
It works for me.
![resim](https://user-images.githubusercontent.com/10170123/58739500-303c1600-8413-11e9-92c0-2148244b524c.png)
This may work for you:
`git clone -b 2.0.5 --single-branch --depth 1 https://github.com/tncga/whats-up-darkness.git`

**Comment by Maxcension** [comment]
It works!
Sorry but i gotta go and i'll be busy tomorrow, but as soon i have so time, i'll try to help you to fix this.
Thanks a lot by the way, you're very kind.
Have a nice night/day!

**Comment by gokberkakdeniz** [comment]
Any difference in the new version (2.0.8)?

**Comment by Maxcension** [comment]
Yeah a little bit, the CPU usage spike is at 55-60%, it's better but it's still there.
