### ISSUE TITLE
QR code has inverted colours

### ISSUE THREAD

**Issue by AMGMNPLK** [tncga/whats-up-darkness#4]
I can't sync the whatsapp desktop because the mobile app doesn't recognize because the QR has inverted colours.

**Comment by gokberkakdeniz** [comment]
Thank you for reporting. You can change "Dark" and "Darker" colors in theme config without waiting new release. A little bit lighter color will work.

**Comment by AMGMNPLK** [comment]
Where could I change that config? I can´t access that option without login.

**Comment by gokberkakdeniz** [comment]
I have changed default color on version 2.0.8, so you don't have to change it again unless you want to customize it. 

If you right click to tray icon, you will see theme settings, by the way.
![resim](https://user-images.githubusercontent.com/10170123/60119695-b71cae00-9787-11e9-878f-e7fc9a82a29f.png)
