### ISSUE TITLE
Error message at launch

### ISSUE THREAD

**Issue by syntaxer** [tncga/whats-up-darkness#5]
Hi,

I've installed 2.0.10 release version on a windows 7 64bit and installs just fine, but when I try to launch, I get this error message:
![image](https://user-images.githubusercontent.com/5112222/67507454-99107d00-f697-11e9-890a-502be5febab3.png)

Am I missing any dependency or something?
I have the official WhatsApp exe installed and that works just fine. 
I don't know if this is relevant, but I also noticed that the app.apsar in the official WhatsApp is 136MB while the one in yours has only 3,90MB

If you need additional information from me, let me know
Thanks

**Comment by gokberkakdeniz** [comment]
Hi, thank you for reporting. While I was releasing version 2.0.10, I  made a mistake. I pushed commits after release. 

You can download version 2.0.11 now. It will work.
